### ISSUE TITLE
请问使用的paddle和paddlehub的版本是那些啊

### ISSUE THREAD

**Issue by hello-word-1** [zhenhao-huang/paddlehub_ernie_emotion_analysis#5]
D:\tool\anaconda3\envs\ernie-cpu\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "D:/lenovo/python-project/paddlehub_ernie_emotion_analysis/finetune_ernie.py", line 2, in <module>
    import paddlehub as hub
  File "D:\tool\anaconda3\envs\ernie-cpu\lib\site-packages\paddlehub\__init__.py", line 54, in <module>
    from paddlehub.compat.task.text_generation_task import TextGenerationTask
  File "D:\tool\anaconda3\envs\ernie-cpu\lib\site-packages\paddlehub\compat\task\text_generation_task.py", line 22, in <module>
    from paddle.fluid.layers import RNNCell, LSTMCell, rnn, BeamSearchDecoder, dynamic_decode
ImportError: cannot import name 'RNNCell' from 'paddle.fluid.layers' (D:\tool\anaconda3\envs\ernie-cpu\lib\site-packages\paddle\fluid\layers\__init__.py)

我用python3.7 paddlehub2.5.0

**Comment by Five-Meng** [comment]
同问

**Comment by zhenhao-huang** [comment]
记不太清，可能是1.8.0
